config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :customers do
    resources :accounts, only: [:new, :create, :show, :index]
  end

  namespace :api do
    namespace :v1 do
      post 'accounts/new_transaction', to: 'accounts#new_transaction'
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :customer
  has_many :transactions

  before_validation :default_balance
  before_validation :default_account_number

  validates :customer, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  def default_balance                 
    self.balance = 0.00 if self.new_record?
  end

  def default_account_number
    self.account_number = rand.to_s[2..10]if self.new_record?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :accounts, dependent: :destroy
  
  validates :pin_number, presence: true, uniqueness: true, length: { is: 4 }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  
  TRANSACTION_TYPES = %w(deposit withdraw)

  before_validation :default_transaction_number

  validates :account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_number, presence: true, uniqueness: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }

  def default_transaction_number
    self.transaction_number = SecureRandom.hex(12) if self.new_record?
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :get_customer
  before_action :set_accounts, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.where(customer_id: params['customer_id'])
  end

  def new
    @account = Account.new customer_id: params['customer_id'] 
  end

  def create
    @account = Account.new customer_id: params['customer_id']

    if @account.save
      redirect_to customer_accounts_path(@customer)
    else
      render 'accounts/new'
    end
  end

  def show
    @account = Account.find params['id']
    if @account.present?
      render 'accounts/show'
    else 
      render 'accounts/new'
    end
  end

  private

  def permitted_params
    params.require(:account).permit(:balance, transaction_attributes: { })
  end

  def get_customer
    @customer = Customer.find_by id: params['customer_id']
  end

  def set_accounts
    @accounts = @customer.accounts
  end
end

app/controllers/api/v1/accounts_controller.rb
module Api
  module V1
    class AccountsController < ApplicationController

      # Bypass authenitcation for basic login 
      skip_before_action :verify_authenticity_token  

      def new_transaction
        account_id = permitted_params[:account_id]
        amount = permitted_params[:amount]
        type = permitted_params[:transaction_type]
        account = Account.find account_id

        errors = TransactionValidator.new(
          account_id: account_id,
          amount: amount,
          transaction_type: type
        ).perform

        if errors.present?
          render json: { errors: errors }, status: :unprocessable_entity
        else
          TransactionCreator.new(
            account_id: account_id,
            amount: amount,
            transaction_type: type
          ).perform

          render json: { balance: account.balance }, status: :created
        end
      end

      private

      def permitted_params
        params.permit(:account_id, :amount, :transaction_type)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params['id'])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      session['customer_id'] = @customer.id
      redirect_to customer_accounts_path(@customer)
    else
      render 'new'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :pin_number)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    customer = Customer.find_by pin_number: params['session']['pin_number']

    if customer
      session['customer_id'] = customer.id
      redirect_to customer_accounts_path(customer)
    else
      flash[:danger] = 'Invalid pin'
      render 'new'
    end
  end

  def destroy
    session.delete 'customer_id'
    @current_customer = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_customer
    @current_customer ||= Customer.find_by id: session['customer_id']
  end
end

app/views/accounts/index.html.erb
<section class="jumbotron">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end"> 
    <%= link_to 'New Account', new_customer_account_path(@customer), class: 'btn btn-secondary float-right' %>
  </div>

  <div class='row'>
    <p>Welcome, <%= current_customer.first_name %> <%= current_customer.last_name %></p>
  </div>

  <h4>Accounts</h4>

  <table class='table'>
    <thead>
      <tr>
        <th scope='col'>Account Number</th>
        <th scope='col'>Balance</th>
        <th scope='col'>Actions</th>
      <tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.account_number %></td>
          <td><%= number_to_currency(account.balance) %></td>
          <td><%= link_to 'View Account', customer_account_path(@customer, account), class: 'btn' %></td>
        </tr>
      <% end %>
      </tr>
    </tbody
  </table>
</section>

app/views/accounts/new.html.erb
<% provide(:title, 'New Account') %>
<div class='container jumbotron new-account'>
  <h1>New Account</h1>
    
  <%= form_for [@customer, @account] do |f| %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/accounts/show.html.erb
<section class="jumbotron">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end p-5"> 
    <%= button_tag :new_transaction, id: 'btn-transaction', class: 'btn btn-secondary float-right' do %>
      New Transaction
    <% end %>
  </div>

  <div class='row'>
    <h4>Account Number # <%= @account.account_number %></h4>

    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>Date</th>
          <th scope='col'>Transaction Type</th>
          <th scope='col'>Amount</th>
        <tr>
      </thead>
      <tbody>
        <% @account.transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.created_at.strftime("%B %e, %Y at %I:%M %p") %>
          <td><%= transaction.transaction_type %></td>
          <td><%= number_to_currency(transaction.amount) %></td>
        </tr>
        <% end %>
        <tr>
          <th>Total Balance</th>
          <th></th>
          <th><%= number_to_currency(@account.balance) %></th>
        </tr>
      </tbody
    </table>
  </div>
</section>

<div id='account-data' data-account-id=<%= @account.id %></div>
<%= render template: 'transactions/new' %>

app/views/customers/new.html.erb
<% provide(:title, 'Sign up') %>
<main class='form-signin new-customer'>
  <h1>Sign up</h1>
    
  <%= form_for @customer do |f| %>
    <div class='row p-3'>
      <%= f.label :first_name, class: 'auto' %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>

    <div class='row p-3'>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>

    <div class='row p-3'>
      <%= f.label :pin_number %>
      <%= f.password_field :pin_number, class: 'form-control' %>
    </div>

    <%= f.submit "Save", class: "btn btn-primary w-100" %>
  <% end %>
</main>

app/views/customers/show.html.erb
<section class="jumbotron">
  <h4>Welcome</h4>
  <%= link_to 'Accounts', customer_account_path(@customer.id) %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link rel='stylesheet' href='https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css' type='text/css'>
    
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class ='navbar navbar-expand-lg navbar-dark bg-dark'>
      <div class='container'>
        <a class='navbar-brand' href="/">ATM</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div id='navbar' class='collapse navbar-collapse'>
          <ul class='navbar-nav mr-sm-2 mt-2 mt-lg-0'>
            <% if current_customer.present? %>
              <li class='nav-item'>
                <%= link_to 'Accounts', customer_accounts_path(current_customer), class: 'nav-link' %>
              </li>
              <li class='nav-item'>
                <%= link_to 'Log Out', logout_path, method: :delete, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class='container'>

      <% if flash[:error] %> 
        <p class='error'><%=h flash[:error] %>
      <% end %>
      <% if flash[:notice] %> 
        <p class='notice'><%=h flash[:notice] %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/new.html.erb
<div id='modal-transaction' class='modal' tabindex='-1'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <h5 class='modal-title'>Add Transaction</h5>
        <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
      </div>
      <div class='modal-body'>
        <div class='row'>
          <div class='col'>
            <div class='alert alert-danger' style='display: none;'>
              <%= @errors %>
            </div>
          </div>
        </div>
        <div class='row g-3'>
          <div class='col-md-6'>
            <%= label_tag 'transaction_type', nil, class: 'form-label' %>
            <%= select_tag 'transaction_type', 
                options_for_select(
                  Transaction::TRANSACTION_TYPES, 
                  selected: Transaction::TRANSACTION_TYPES.first,
                  ), 
                id: 'transaction-type', 
                class: 'btn btn-secondary dropdown-toggle form-control' 
            %>
          </div>
          <div class='col-md-8'>
            <%= label_tag 'amount', nil, class: 'form-label' %>
            <%= text_field_tag 'amount', params[:amount], id: 'transaction-amount', class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Close</button>
        <button type='button' id='btn-submit' class='btn btn-primary'>Save</button>
      </div>
    </div>
  </div>
</div>